//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIWithDB2EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACT
    {
        public short ACTNO { get; set; }
        public string ACTKWD { get; set; }
        public string ACTDESC { get; set; }
    
        public virtual ACT ACT1 { get; set; }
        public virtual ACT ACT2 { get; set; }
    }
}
