//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIWithDB2EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_PHOTO
    {
        public string EMPNO { get; set; }
        public string PHOTO_FORMAT { get; set; }
        public byte[] PICTURE { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
