//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIWithDB2EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.DEPARTMENTs = new HashSet<DEPARTMENT>();
            this.EMP_PHOTO = new HashSet<EMP_PHOTO>();
            this.EMP_RESUME = new HashSet<EMP_RESUME>();
            this.PROJECTs = new HashSet<PROJECT>();
        }
    
        public string EMPNO { get; set; }
        public string FIRSTNME { get; set; }
        public string MIDINIT { get; set; }
        public string LASTNAME { get; set; }
        public string WORKDEPT { get; set; }
        public string PHONENO { get; set; }
        public Nullable<System.DateTime> HIREDATE { get; set; }
        public string JOB { get; set; }
        public short EDLEVEL { get; set; }
        public string SEX { get; set; }
        public Nullable<System.DateTime> BIRTHDATE { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<decimal> BONUS { get; set; }
        public Nullable<decimal> COMM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DEPARTMENT DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_PHOTO> EMP_PHOTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMP_RESUME> EMP_RESUME { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PROJECT> PROJECTs { get; set; }
    }
}
