//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIWithDB2EF.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SAMPLEEntities : DbContext
    {
        public SAMPLEEntities()
            : base("name=SAMPLEEntities")
        {
            Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACT> ACTs { get; set; }
        public virtual DbSet<CATALOG> CATALOGs { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMERs { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENTs { get; set; }
        public virtual DbSet<EMP_PHOTO> EMP_PHOTO { get; set; }
        public virtual DbSet<EMP_RESUME> EMP_RESUME { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEEs { get; set; }
        public virtual DbSet<INVENTORY> INVENTORies { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCTSUPPLIER> PRODUCTSUPPLIERs { get; set; }
        public virtual DbSet<PROJACT> PROJACTs { get; set; }
        public virtual DbSet<PROJECT> PROJECTs { get; set; }
        public virtual DbSet<PURCHASEORDER> PURCHASEORDERs { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIERS { get; set; }
        public virtual DbSet<ADEFUSR> ADEFUSRs { get; set; }
        public virtual DbSet<EMPPROJACT> EMPPROJACTs { get; set; }
        public virtual DbSet<ORG> ORGs { get; set; }
        public virtual DbSet<STAFF> STAFFs { get; set; }
        public virtual DbSet<STAFFG> STAFFGs { get; set; }
    }
}
