//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIWithDB2EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORG
    {
        public short DEPTNUMB { get; set; }
        public string DEPTNAME { get; set; }
        public Nullable<short> MANAGER { get; set; }
        public string DIVISION { get; set; }
        public string LOCATION { get; set; }
    }
}
