//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIWithDB2EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJACT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PROJACT()
        {
            this.EMPPROJACTs = new HashSet<EMPPROJACT>();
        }
    
        public string PROJNO { get; set; }
        public short ACTNO { get; set; }
        public Nullable<decimal> ACSTAFF { get; set; }
        public System.DateTime ACSTDATE { get; set; }
        public Nullable<System.DateTime> ACENDATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPPROJACT> EMPPROJACTs { get; set; }
        public virtual PROJECT PROJECT { get; set; }
    }
}
