//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIWithDB2EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PURCHASEORDER
    {
        public long POID { get; set; }
        public string STATUS { get; set; }
        public Nullable<long> CUSTID { get; set; }
        public Nullable<System.DateTime> ORDERDATE { get; set; }
        public string PORDER { get; set; }
        public string COMMENTS { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
