//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPIWithDB2EF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class STAFFG
    {
        public short ID { get; set; }
        public string NAME { get; set; }
        public Nullable<short> DEPT { get; set; }
        public string JOB { get; set; }
        public Nullable<short> YEARS { get; set; }
        public Nullable<decimal> SALARY { get; set; }
        public Nullable<decimal> COMM { get; set; }
    }
}
